# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'tryFunNew' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for tryFunNew
  pod 'Masonry', '~> 1.0.2'
  pod 'Reveal-iOS-SDK', '~> 1.6.2'
  pod 'MagicalRecord', '~> 2.3.2'
  pod 'MyLayout', '~> 1.3.8'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'MLLabel', '~> 1.10.3'
  pod 'MLEmojiLabel', '~> 1.0.2'
  pod 'YYKit', '~> 1.0.9'
  pod 'NSLogger'
  pod 'MJRefresh', '~> 3.1.14'
end
